version: '3.8'

services:
  z-image:  # تم تغيير الاسم هنا ليتطابق مع طلب Dokploy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z_image_container
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
      - ZIMAGE_ATTENTION=math
      - TORCH_DEVICE=cpu
    volumes:
      - ./ckpts:/app/ckpts
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G
