version: '3.8'

services:
  z-image:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z_image_app
    ports:
      - "7860:7860"
    environment:
      - DEVICE=cpu
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
    restart: unless-stopped
    # تم حذف قسم النشر والـ GPU تماماً ليعمل على خادم Hostinger
